apiVersion: v1
kind: Pod
metadata:
  name: myapp-main-db-pod
  labels:
    app.kubernetes.io/name: myapp-main-db
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    env:
      - name: MYSQL_PORT
        value: "GET FROM CONFIG PROPERTIES ???"
    ports:
      - containerPort: <??? HOW TO SET FROM MYSQL_PORT ENV VAR ABOVE ???>
    volumeMounts:
      - name: myapp-main-db-volume
        mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-main-db-service
  labels:
    app.kubernetes.io/name: myapp-main-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-main-db-deployment
  labels:
    app.kubernetes.io/name: myapp-main-db
spec:
  strategy:
    type: Recreate
  replicas: 2
